
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - callcenter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: call-dispatcher-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_REDIS_HOST=redis
    networks:
      - callcenter-network

volumes:
  redis-data:

networks:
  callcenter-network:
